# File Paths
classes_file_path: './classes/yolov3_classes.txt'
model_structure_file_path: './models/yolov3.cfg'
model_weights_file_path: './models/yolov3.weights'
test_data_path: './data/test_images/'
test_image: './data/test_images/image_1.jpeg'

# URLs
nn_weights_url: 'https://pjreddie.com/media/files/yolov3.weights'

# Blob from Image Parameters
blob_size: [416, 416]
blob_scale_factor: 0.00392
blob_swap_rb: True
blob_crop: False

# Inference Parameters
detection_confidence_threshold: 0.5
non_max_suppression_threshold: 0.4