# File Paths
classes_file_path: './classes/yolov3_classes.txt'
model_structure_file_path: './models/yolov3.cfg'
model_weights_file_path: './models/yolov3.weights'
test_data_path: './data/test_images/'

# URLs
nn_weights_url: 'https://pjreddie.com/media/files/yolov3.weights'
